name: github pages scaladoc
on:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Retrieve the content of the repository
      - uses: actions/setup-java@v2 # Set up a jdk and sbt
      
      
      - name: test
        if: success()
        run: sbt test
      - name: scaladoc # Custom action consisting of a shell command
        if: success()
        run: sbt doc
      - name: publicdir
        if: success()
        run: |
          mkdir public
          mv target/scala-3*/api/* public/
          
      - name : Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: publicdir
        if: success()
        run: |
          sbt package
          jar_path=$(find ./target/ -name *.jar)
          cp $jar_path .
      
      - name : realease
        if: success()
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.jar
  
